CREATE TABLE IF NOT EXISTS event(
  key UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	teamkey TEXT NOT NULL REFERENCES team(key) ON DELETE CASCADE,
  name TEXT NOT NULL,
  fullDay BOOLEAN NOT NULL DEFAULT FALSE,
	startTime DATETIME NULL,
	endTime DATETIME NULL
);